### ISSUE TITLE
Week 8 (Due Nov. 19) to-do

### ISSUE THREAD

**Issue by LilacHo** [UndefiedCse/Heat-Island#20]
Week 8 (Due Nov. 19): Get all the data ready
- [x] Building data @JornsenChao 
- [x] Weather data @LilacHo

**Comment by LilacHo** [comment]
I submitted a pull request containing a sample of weather data. The development of a data scraper is in progress, which will allow for daily updates of the data file with new information. I hope this sample of weather data can let us start the development of machine learning.

**Comment by LilacHo** [comment]
@JornsenChao How is your progress in gathering data on building heights?

**Comment by JornsenChao** [comment]
I new a folder called data.

**Comment by JornsenChao** [comment]
Shall we discuss tomorrow about an actual data covering range? @LilacHo 
I can easily reset the vertex of my range and download the data.
![image](https://github.com/UndefiedCse/Heat-Island/assets/106364994/91f028bc-b0c8-4c26-a799-17bdadc7464b)
The data is now cleaned, with three column and distribution like this 
![image](https://github.com/UndefiedCse/Heat-Island/assets/106364994/49b5591c-a650-40e5-9054-aff2d330591e)

**Comment by LilacHo** [comment]
I aimed at Seattle but we can definitely talk about it tomorrow.
![Seattle](https://github.com/UndefiedCse/Heat-Island/assets/103151283/1748d98a-dbe7-45fd-a736-bfad6034fb13)
