### ISSUE TITLE
Final! Week 11 (Due Dec. 13) to-do

### ISSUE THREAD

**Issue by LilacHo** [UndefiedCse/Heat-Island#25]
Wrap up, write the necessary doc, prepare for the presentation

**Comment by LilacHo** [comment]
@JornsenChao Can you specify how to get raw_terrain_fn = "example_dem.tif". Or if it's a click of download, please upload it in 'data'.

**Comment by LilacHo** [comment]
@JornsenChao I wasn't able to keep working because of missing raw files. Unable to fill the gap of height_acquire. Additionally, progressing with the 'geo_process' is not feasible without the raw files, as their structure is crucial for the process.

'''read existing files'''
# building, extent, weather, boundary, terrain (set crs to 4326)
raw_building = gpd.read_file(raw_building_path)
raw_extent = gpd.read_file(raw_extent_path)
raw_weather = pd.read_csv(raw_weather_path) (I think we have this already)
raw_boundary = gpd.read_file(raw_boundary_path) (I think we also have this? the city limit?)

**Comment by JornsenChao** [comment]
Please use this link to download the original geotif. My code includes trim the original tif with extent. (or can be the city boundary).
https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/historical/n48w123/USGS_13_n48w123_20230608.tif

I tried to upload but github won't allow big files
@LilacHo

**Comment by LilacHo** [comment]
Do we really need pylint workflow? I guess it is zero tolerance until it gets 10/10. My opinion is that if flake8 works the same, we don't need both. @krittin-kulrat @loriwon-uw

**Comment by krittin-kulrat** [comment]
I think we should go with `pylint` and ditch `flake8`. The reason being, `pylint` does a more thorough job by flagging missing function documentation which is more important.

**Comment by LilacHo** [comment]
I understand. Can we use it as our own debugger and if it seriously cannot pass on Wed, we switch over? We can decide my suggestion later... But it gonna fail on my end forever. I just don't know how to fulfil all of its requests like "heat_island/height_acquire.py:236:0: R0914: Too many local variables (29/15) (too-many-locals)". If I genuinely addressed the issue of excessive local variables, it was necessary to reconstruct the function from scratch.

**Comment by krittin-kulrat** [comment]
I think it's fine considering timeframe. I'm going to create a pull request so you can continue working on other stuff. Do you need any help? Here is [my Zoom Link](https://washington.zoom.us/j/98341197368).

**Comment by LilacHo** [comment]
I am good at this point. Thank you for your offer! It is a function of around 200 lines of code so it's understandable to have too many local variables. I did try to split it into pieces (I promise I really tried) but for the sake of time, the most important is that it runs successfully instead of worrying about the warning.

**Comment by JornsenChao** [comment]
I made a pull request, add functions to get building data and terrain data from a given study boundary.

**Comment by JornsenChao** [comment]
https://drive.google.com/drive/folders/1LRoYHLRKRPzDxGWpCMemAKpcMFi9taGH?usp=sharing
here is the output file from these above functions. larger than 25mb so have to share through drive.
but I believe this module could get you these data.
